# Generated by Django 4.1.3 on 2022-11-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.TextField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='ProfilePhotos')),
                ('nationalality', models.TextField(max_length=200)),
                ('enquired', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='transcactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttype', models.TextField(max_length=100)),
                ('tamount', models.TextField(max_length=60)),
                ('tmode', models.TextField(max_length=150)),
            ],
        ),
    ]
