# Generated by Django 4.1.3 on 2022-12-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nationalality',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transcactions',
            name='tamount',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='transcactions',
            name='tmode',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='transcactions',
            name='ttype',
            field=models.CharField(max_length=100),
        ),
    ]
